#Estimates Empirical assemblages of geomorphic units as percent of bankful area of each unit type for
#reach selections from RSselection.R. 

#Natalie Kramer (n.kramer.anderson@gmail.com)
#Last Updated Aug 10 2019

#Documentation available on 
#https://natalie-kramer.github.io/GeomorphicUpscale/

# To Do ------------------------------------------------------------

# Dependencies ------------------------------------------------------------

require(ggplot2)
require(dplyr)
require(tidyr)

source(paste(GUPdir, "\\scripts\\plot.colors.R", sep=""))
source(paste(GUPdir, "\\scripts\\functions.R", sep=""))

###user variables defined in UpscaleWrapper.R###
PROJdir=PROJdir  #directory path to local project
GUPdir=GUPdir   #directory path to Github repo
selections=selections #directory path to input selections file generated by RSselection.R
gu.type=gu.type      #Options: UnitForm, GU #UnitShape not available at this time since I don't have maps of these in the database
RSlevels=RSlevels #optional vector argument to set RS factor order in graphs and displays, leave as c("") if alphabetical is desired
plottype=plottype   #Options: .tiff, .png, .pdf, "none"
myscales=myscales #Options: fixed or free x/y axis scales for tiled plot output

# set up data refs and output file structure  ------------------------------------------------------------------------

print("set up data refs and output file structure...")

#Create Output subdirectories based on user variable choices
create.subdirs(PROJdir, c("Outputs", "assemblage",  gu.type, "by.unit"))

#specify OUTput directory as variable
OUTdir=paste(PROJdir, "Outputs","assemblage", gu.type, "by.unit", sep="\\")

#Specify location of input metric tables
GUTdir=paste(GUPdir,"\\Database\\Metrics" , sep="")

#specify GUT output layer to draw data from based on gu.type
#May need to change this in the future? depended on file naming conventions.
if(gu.type=="GU"){layer="Tier3_InChannel_GU"}
if(gu.type=="UnitForm" | gu.type=="UnitShape"){layer="Tier2_InChannel_Transition" }

#make list of GUT output matching layer
GUToutputlist=list.files(GUTdir)[grep(layer, list.files(GUTdir)) ]


# Reads in and preps Unit Data data ----------------------------------------------------------

print("reading in and reformatting data...")

#Read in Unit Data and convert to long data format
unitmetrics=read.csv(paste(GUTdir,GUToutputlist[grep("Unit_GUT", GUToutputlist)],sep="\\"),stringsAsFactors=F)%>%
    filter(gut.layer==gu.type)%>%
    select(-gut.layer)%>%
    gather(value="value", key="variable", 3:13)%>%
    mutate(ROI="bankfull")
  
#combine Unit data with selections
unitdata=join.selection(selections, unitmetrics)%>%
  filter(!is.na(unit.type))
  
# summarize variables in GUT unit summary ----------------------------------------------

#summarize variables in GUT summary
print("making site summary tables and plots...")

#prints stats for each unit into OUTdir
print("for RScond")
stats.RScond=make.outputs.unit(unitdata, poolby="RScond", gu.type=gu.type, plottype=plottype, OUTdir=OUTdir, RSlevels=RSlevels)
print("for RS")
stats.RS=make.outputs.unit(unitdata, poolby="RS", gu.type=gu.type, plottype=plottype, OUTdir=OUTdir, RSlevels=RSlevels)
print("for All")
stats=make.outputs.unit(unitdata, poolby="", gu.type=gu.type, plottype=plottype, OUTdir=OUTdir, RSlevels=RSlevels)


# estimating assemblage estimates from average proportions ----------------------------------------------

print("making assemblage tables and plots...")

#function that Makes renormalized assemlages and plots them (percentages of area for each unit within bankfull for different poolby specifications)
assemblage.proportions=function(mystats, poolby, myROI="bankfull", myplottype=plottype, myOUTdir=OUTdir){
  
  #filter data for just proportions of reach occupied by each unit
  assemblage=mystats%>%filter(variable=="area.ratio", ROI==myROI)%>%
    select(-sd,-med,-min,-max,-n, -tot)
  
  #spreads table grouped by poolby so that unit types are converted to columns.
  if(poolby=="RScond"){
    assemblage1=assemblage%>%group_by(RS, Condition)%>%
      spread(key="unit.type", value=avg)%>%
      ungroup
    myOUTdir=paste(myOUTdir,"byRScond", sep="\\")
  }
  
  if(poolby=="RS"){
    assemblage1=assemblage%>%group_by(RS)%>%
      spread(key="unit.type", value=avg)%>%
      ungroup
    myOUTdir=paste(myOUTdir,"byRS", sep="\\")
  }
  
  if(poolby==""){
    assemblage1=assemblage%>%
      spread(key="unit.type", value=avg)
    myOUTdir=paste(myOUTdir,"byAll", sep="\\")
  }
  
  #makes list of unit types and find starting and ending column for renormalization
  unitlist=levels(as.factor(as.character(mystats$unit.type)))
  startcol=length(names(assemblage1))-length(unitlist)+1
  endcol=length(names(assemblage1))
  
  #Renormalize proportions to sum to 100
  assemblage2=assemblage1%>%ungroup()%>%
    mutate(SUM1=select(.,startcol:endcol)%>%apply(1, sum, na.rm=T))%>%#make sum across proportions
    mutate_at(startcol:endcol, funs(./SUM1))%>%#renormalize columns
    mutate(SUM=select(.,startcol:endcol)%>% apply(1, sum, na.rm=T))%>% #check math
    select(-SUM1)
  
  print(paste("assemblage.csv files written to: ", myOUTdir,  sep=" "))
  write.csv(assemblage2, paste(myOUTdir,"\\assemblage.csv", sep=""), row.names=F)
  
  print(paste("myplottype= ", myplottype))
  if(myplottype!="none"){
    print("making plots...")
    assemblage.plot(assemblage2, poolby, startcol, endcol, myfacet="value", myOUTdir=myOUTdir)
  }
  
  return(assemblage2)
}
#function to plot assemblage. Used within assemblage.proportions function
assemblage.plot=function(assemblagedata, poolby, startcol, endcol, myfacet="value", myOUTdir){
  
  #Read in and manipulate data for plotting
  mydata=gather(assemblagedata, key="Unit", value="value", startcol:endcol)%>%select(-SUM)
  
  #sets colors and factor orders for plotting
  
  #condition levels for plots hard coded as "poor", "mod", "good" to show up in correct order
  if(poolby=="RScond"){
    mydata$Condition=factor(mydata$Condition, levels=condition.levels)
    print("Condition levels")
    print(levels(mydata$Condition))
    print("Condition colors=")
    print(condition.fill)}
  
  #set RSlevel order
  if(poolby!=""){
    if(is.na(RSlevels)[1]==F){
      mydata$RS=factor(mydata$RS,levels=RSlevels)
      mydata$RS}
    print("RS levels=")
    print(levels(mydata$RS))
  }
  
  a=set.levels.colors(mydata, gu.type, GUPdir, unitcolname="Unit")
  unitcolors=a$unitcolors
  mydata=a$mydata
  
  #makes assemblage plots
  if(poolby==""){
    p1 <- ggplot() +
      geom_bar(data=mydata%>%distinct(), aes(y=value, x=ROI, fill=Unit), stat="identity",
               position='stack') +
      scale_fill_manual(values = unitcolors)
  }
  
  if(poolby=="RS"){
    p1 <- ggplot() +
      geom_bar(data=mydata%>%distinct(), aes(y=value, x=RS, fill=Unit), stat="identity",
               position='stack') +
      scale_fill_manual(values = unitcolors)
    print(p1)
  }
  
  if(poolby=="RScond"){
    facetcol=which(colnames(mydata)==myfacet)
    p1 <- ggplot() +
      geom_bar(data=mydata%>%distinct(), aes(y=value, x=Condition, fill=Unit), stat="identity",
               position='stack') +
      scale_fill_manual(values = unitcolors)+
      facet_grid( ~ RS) +
      facet_wrap( ~ RS, scales='free')
    print(p1)
  }
  
  #saves assemblage plots 
  if(plottype==".pdf"){
    ggsave(paste(myOUTdir, "assemblage.pdf", sep="\\"), plot=p1, width = 10, height = 7 )
  }
  
  if(plottype==".png"){
    ggsave(paste(myOUTdir, "assemblage.png", sep="\\"), plot=p1, width = 10, height = 7)
  }
  
  if(plottype==".tiff"){
    ggsave(paste(myOUTdir,"assemblage.tiff", sep="\\"), plot=p1, width = 10, height =7)
  }
  
  print(paste("assemblage plot written to: ", myOUTdir,  sep=" "))
}



#writes assemblages and creates plots based on specified poolby
print("for RScond")
assemblage.proportions(stats.RScond, poolby="RScond")
print("for RS")
assemblage.proportions(stats.RS, poolby="RS")
print("for All")
assemblage.proportions(stats, poolby="")

print(paste("files written to: ", OUTdir,  sep=" "))

# cleaning up ----------------------------------------------

print("erasing temporary variables")

keepvars=c("PROJdir","GUPdir", "selections",
           "plottype", "myscales" , "RSlevels", "gu.type")
rm(list=ls()[-match(x = keepvars, table = ls())])

print("done")
  
  
