#Summarizes geoindicators by RS selctions from database
#reach selections from RSselection.R. 

#Natalie Kramer (n.kramer.anderson@gmail.com)
#Last Updated July 13 2019

#Documentation available on 
#https://natalie-kramer.github.io/GeomorphicUpscale/


# To Do -------------------------------------------------------------------

#make pool by RS and Condition separate output folders  

# Dependencies -------------------------------------------------------------------

require(ggplot2)
require(dplyr)
require(tidyr)

source(paste(GUPdir, "\\scripts\\plot.colors.R", sep=""))
source(paste(GUPdir, "\\scripts\\functions.R", sep=""))

PROJdir=PROJdir  #directory path to local project
GUPdir=GUPdir   #directory path to Github repo
selections=selections #directory path to input selections file generated by RSselection.R
RSlevels=RSlevels #optional vector argument to set RS factor order in graphs and displays, leave as  NA if alphabetical is desired
plottype=plottype   #Options: .tiff, .png, .pdf, "none"
myscales=myscales #Options: fixed or free x/y axis scales for tiled plot output

# set up data refs and output file structure  ------------------------------------------------------------------------

#Create Output subdirectory
basesubdir=c("Outputs", "selections", "geoindicators")
create.subdirs(PROJdir, basesubdir)

#specify OUTput directory 
OUTdir=paste(PROJdir, "Outputs","selections", "geoindicators", sep="\\")

#delete any existing files in Output from previous runs
unlink(paste(OUTdir,"\\*", sep=""), recursive=T)

#Specify location of input metric tables
GUTdir=paste(GUPdir,"\\Database\\Metrics" , sep="")

#create long format for selections of quatitative data
geoindicators=selections%>%select(RS, Condition, visit.id, Gradient:Sndf)%>%
  gather(value="value", key="variable", 4:17)%>%
  mutate(unit.type=NA, ROI="NA")



# making summaries  ------------------------------------------------------------------------

print("making summary outputs...")

#summarized by All
make.outputs(geoindicators,poolby="", plottype=".pdf", OUTdir=OUTdir, RSlevels=RSlevels)
make.outputs(geoindicators, poolby="", plottype=".png", OUTdir=OUTdir, RSlevels=RSlevels)

#summarized by River Style (RS)
make.outputs(geoindicators,poolby="RS", plottype=".pdf", OUTdir=OUTdir, RSlevels=RSlevels)
make.outputs(geoindicators, poolby="RS", plottype=".png",OUTdir=OUTdir, RSlevels=RSlevels)

#summarized by RS and Condition
make.outputs(geoindicators,poolby="RScond", plottype=".pdf", OUTdir=OUTdir, RSlevels=RSlevels)
make.outputs(geoindicators, poolby="RScond", plottype=".png", OUTdir=OUTdir, RSlevels=RSlevels)

print(paste("Files written to", OUTdir , sep= " "))

# cleaning up ------------------------------------------------------------------------


print("done. erasing temporary variables")

keepvars=c("PROJdir","GUPdir", "selections", 
           "plottype", "myscales" , "RSlevels", "gu.type")
rm(list=ls()[-match(x = keepvars, table = ls())])


