#Copy maps to new directories to quickly verify subsetted data as good representations for desired 
#river style and condition-------------------------------------------------------------

#Natalie Kramer (n.kramer.anderson@gmail.com)
#Last Updated July 17, 2019

# To Do -------------------------------------------------------------------
#clean up annotation

# Dependencies -------------------------------------------------------------------

require(ggplot2)
require(dplyr)
require(tidyr)

source(paste(GUPdir, "\\scripts\\plot.colors.R", sep=""))
source(paste(GUPdir, "\\scripts\\functions.R", sep=""))

PROJdir=PROJdir  #directory path to local project
GUPdir=GUPdir   #directory path to Github repo
selections=selections #directory path to input selections file generated by RSselection.R
#hardcoded variables- #Need to think about this...could make more variable...
idcolname="visit.id"
idcolname2=NA

# set up data refs and output file structure  ------------------------------------------------------------------------


#create outputdirectory
source(paste(GUPdir, "\\scripts\\functions.R", sep=""))
create.subdirs(PROJdir, c("Outputs", "selections", "maps"))

#specify output directory
OUTdir=paste(PROJdir, "Outputs","selections", "maps", sep="\\")

#delete any existing files in Output from previous runs
unlink(paste(OUTdir,"\\*", sep=""), recursive=T)

#specify location of maps from database
MAPrepo=paste(GUPdir,"\\Database\\Maps", sep="")  

#make a list of maps in the repo for specified layer
#link output GUT layers to gu.type variables
if(gu.type=="GU"){layer="Tier3_InChannel"}
if(gu.type=="UnitForm"){layer="Tier2_InChannel_Transition" }
maplist=paste(MAPrepo,
              list.files(MAPrepo)[grep(layer, list.files(MAPrepo))],sep="\\")#list of files in MAPrepo



  
 #find numeric column number corresponding to River Style and ID columns 
 copy.maps=function(poolby){ 
  
   #poolby should correspond to column name in selections 
   RScolname=poolby 
   
   RScol=which(colnames(selections)==RScolname)
  idcol=which(colnames(selections)==idcolname)
  if(is.na(idcolname2)==F){
  idcol2=which(colnames(selections)==idcolname2)}
  
  #Make a list of subfolders to print to
  RSlist=levels(selections[,RScol]) #create list of RS 
  print("RSlist")
  print(RSlist)
 
print(paste("copying maps, pooling by", poolby))
  #loops down list of riverstyles and copies relevent visit maps from Map Repo
  i=1
  for(i in 1:length(RSlist)){
    RS=RSlist[i]
    create.subdirs(OUTdir, c(RS, gu.type))
    RSdir=paste(OUTdir, RS, gu.type, sep="\\") #create output directory for RS and condition
    #if (file.exists(RSdir)==F){dir.create(RSdir)}  #make folder corresponding to RS and condition if it doesnt exist already
    
    rows=which(selections[,RScol]==RSlist[i]) #vector of rows related to given RS and Condition
    for(i in 1:length(rows)){
      ID=selections[rows[i],idcol] 
      mapfile=maplist[grep( paste("_",as.character(ID),"_",sep="") , maplist)]
      if(file.exists(mapfile)){
        file.copy(mapfile, RSdir, overwrite=T)} else {print(paste("map for", ID, "does not exist", sep=" "))
        }
    }
  }
  
  
 }
 
 copy.maps("RS")
 copy.maps("RScond")
 
  print(paste(gu.type, "maps printed to", OUTdir, sep=" "))
  
  # cleaning up ------------------------------------------------------------------------
  
  
  print("done. erasing temporary variables")
  
  keepvars=c("PROJdir","GUPdir", "selections", 
             "plottype", "myscales" , "RSlevels", "gu.type")
  rm(list=ls()[-match(x = keepvars, table = ls())])




